# Generated by Django 3.2.12 on 2023-08-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('price', models.FloatField()),
                ('ingredients', models.CharField(max_length=280)),
            ],
        ),
    ]
