# Generated by Django 3.2.12 on 2023-08-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20230824_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='desc',
            field=models.CharField(default='No description added yet.', max_length=520),
        ),
    ]
